# worker/pipeline/gemini.py

import json
import logging
import os
from typing import List, Dict, Any, Optional

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

PROJECT_ID = os.getenv("GCP_PROJECT_ID")
LOCATION = "us-central1"
MODEL_NAME = "gemini-2.5-flash"

GENERATION_CONFIG = types.GenerateContentConfig(
    temperature=0.2,
    max_output_tokens=2048,
    response_mime_type="application/json",
)

_client: genai.Client | None = None


def get_gemini_client() -> genai.Client:
    """
    Return an initialised Gemini client using Vertex AI backend.
    Lazy init — ADC handles auth automatically.
    """
    global _client
    if _client is None:
        _client = genai.Client(
            vertexai=True,
            project=PROJECT_ID,
            location=LOCATION,
        )
        logger.info(f"Gemini client initialised — project: {PROJECT_ID}, location: {LOCATION}, model: {MODEL_NAME}")
    return _client


async def generate_summary(
    transcript: List[Dict[str, Any]],
    scenes: List[Dict[str, Any]],
    duration_seconds: int,
    job_id: str = "unknown",
) -> Dict[str, Any]:
    """
    Generate AI summary, chapters, highlights, sentiment, and action items.

    STUB — Week 4 replaces this body with a real Vertex AI Gemini call.
    The function signature, parameters, and return shape are final.

    Returns correctly-shaped placeholder data so:
    - The orchestrator can call this today without changes
    - GET /result returns the full response shape for frontend development
    - Week 4 is purely a Gemini API implementation, not an orchestrator refactor
    """
    transcript_preview = " ".join(
        w["word"] for w in transcript[:30]
    ) if transcript else "No speech detected."

    logger.info(
        f"[{job_id}] Gemini stub called — "
        f"words: {len(transcript)}, scenes: {len(scenes)}, duration: {duration_seconds}s"
    )

    # Derive stub chapters from scene count — three equal thirds
    third = duration_seconds // 3 if duration_seconds > 0 else 1
    chapters = [
        {"title": "Introduction", "startTime": 0, "endTime": third},
        {"title": "Main content", "startTime": third, "endTime": third * 2},
        {"title": "Conclusion", "startTime": third * 2, "endTime": duration_seconds},
    ]

    # Derive stub highlights from scene midpoints (max 3)
    highlights = []
    for scene in scenes[:3]:
        midpoint = round((scene["startTime"] + scene["endTime"]) / 2, 1)
        top_label = scene["labels"][0] if scene.get("labels") else "scene"
        highlights.append({
            "timestamp": midpoint,
            "description": f"Scene featuring {top_label} (stub — Gemini generates real descriptions in Week 4)",
        })

    return {
        "summary": (
            f"This {duration_seconds // 60}-minute video contains {len(scenes)} scenes "
            f"and {len(transcript)} transcribed words. "
            f"Transcript begins: \"{transcript_preview}...\" "
            f"(AI summary will be generated by Gemini in Week 4.)"
        ),
        "chapters": chapters,
        "highlights": highlights,
        "sentiment": "neutral",
        "actionItems": [],
    }